# Site
name: "Investing Ninja"
title: "Investing Ninja"
description: "Invest like a Ninja"
meta_description: "Invest like Ninja"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'ninja@hasitha.org'
google_analytics: 'UA-27816058-3'
disqus: 'investingninja'
sharethis: '<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5d0a0b091449a300127e1b26&product=sticky-share-buttons' async='async'></script>'

# Authors
authors:
  ninja:
    name: Ninja
    display_name: Investing Ninja
    gravatar: 786aa7b9136dd96044c7c227fb68d9c5
    email: ninja@hasitha.org
    web: https://www.investingninja.club
    twitter: https://twitter.com/investingninja
    description: "We are a team of professional investors and entrepreneurs who are actively seaking Financial Freedom."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
